### ISSUE TITLE
Restore "external" icon for non-state.gov links

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#229]
The old hsg indicated links to external (i.e., those outside of state.gov) sites, such as to Metagrid links. 

![Icon_External_Link](https://upload.wikimedia.org/wikipedia/commons/6/64/Icon_External_Link.png)

We also had a mechanism to override this icon for external links to our own postings on other sites like our Twitter feed, by adding `@class="not-external"`, etc. to links.

On the old site we used this CSS, although I'm not wedded to this approach:

```css
a[href ^='http://'] {
    padding-right: 13px;
    background: url(//upload.wikimedia.org/wikipedia/commons/6/64/Icon_External_Link.png) no-repeat right center;
}
/* replace background with:
url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAFZJREFUeF59z4EJADEIQ1F36k7u5E7ZKXeUQPACJ3wK7UNokVxVk9kHnQH7bY9hbDyDhNXgjpRLqFlo4M2GgfyJHhjq8V4agfrgPQX3JtJQGbofmCHgA/nAKks+JAjFAAAAAElFTkSuQmCC") no-repeat scroll right center transparent;
*/
a[href ^='https://'] {
    padding-right: 13px;
    background: url(//upload.wikimedia.org/wikipedia/commons/6/64/Icon_External_Link.png) no-repeat right center;
}
a.not-external {
    padding-right: 0;
    background: none;
}
.tweet a {
    padding-right: 0;
    background: none;
}
a[href *='state.gov'] {
    padding-right: 0;
    background: none;
}
```
